### ISSUE TITLE
Flatten + zip w/ CSV generates Nulls

### ISSUE THREAD

**Issue by andypern** [tdunning/log-synth#21]
For JSON the flatten method seems to work OK;

Here's schema file:

[
{
    "name": "z",
    "class": "flatten",
    "value": { "class": "zip", "fields": "latitude, longitude"}
}

]​

w/ JSON:

{"z-longitude":"-85.96","z-latitude":"39.35"}
{"z-longitude":"-74.63","z-latitude":"44.97"}

when I specify CSV:

null
null
null

I tried verbose=true/false, same thing.

**Comment by tdunning** [comment]
Changed flatten semantics to make this make more sense to users.
