### ISSUE TITLE
Schema to generate nested JSON

### ISSUE THREAD

**Issue by deeptiantony** [tdunning/log-synth#28]
Hello, I would like to know if there is any class/schema which can be used to generate nested JSON (sample as below)

Example : 

{
	"name": {
		"first": "David",
		"last": "Joseph"
	},
	"student": {
		"details": {
			"school.id": "1010",
			"school.name": "Brooklands"

		}
	},
	"version": "1.0.1"
}

Thanks in advance,
Deepti

**Comment by tdunning** [comment]
Sure.  But first, to build suspense, here is some output that I generated:
```
{
  "name":{"first":"Marcelene","last":"Gillette"},
  "student":{
    "details":{"school.id":7608,"school.name":"Lloyd Burton Junior High School"}}}
{
  "name":{"first":"Samuel","last":"Colston"},
  "student":{
    "details":{"school.id":3555,"school.name":"Kenneth Smith Junior High School"}}}
{
  "name":{"first":"Jan","last":"Acton"},
  "student":{
    "details":{"school.id":4295,"school.name":"Jeanette Harden Elementary School"}}}
```

There are a few tricks that I used here:

1) the [map type](https://github.com/tdunning/log-synth/blob/master/README.md#map) allows me to generate a structure for the name and the details structure. 

2) the [join combined with the sequence](https://github.com/tdunning/log-synth/blob/master/README.md#sequence) type allows me to build the school name by combining a name and a randomly selected string.

Here is the schema (it looks fancier than it is):

```
[{
	"name": "name",
	"class": "map",
	"value": [{
		"name": "first",
		"class": "name",
		"type": "first"
	}, {
		"name": "last",
		"class": "name",
		"type": "last"
	}]
}, {
	"name": "student",
	"class": "map",
	"value": [{
		"name": "details",
		"class": "map",
		"value": [{
			"name": "school.id",
			"class": "int",
			"min": 1000,
			"max": 9999
		}, {
			"name": "school.name",
			"class": "join",
			"separator": " ",
			"value": {
				"class": "sequence",
				"length": 2,
				"array": [{
					"class": "name",
					"type": "first_last"
				}, {
					"class": "string",
					"dist": {
						"High School": 1,
						"Junior High School": 2,
						"Elementary School": 5
					}
				}]
			}
		}]
	}]
}]
```

**Comment by tdunning** [comment]
Added this example to the README.

See https://github.com/tdunning/log-synth/blob/master/README.md#longer-examples

**Comment by deeptiantony** [comment]
This worked. Thanks!!

**Comment by tdunning** [comment]
Tell others!

**Comment by deeptiantony** [comment]
Quick question. Is there any way to convert an integer to string? Like generating random numbers using class as int and converting them to string while generating JSON data.

**Comment by tdunning** [comment]
Joining with a string should work. Haven't tried it, however.

**Comment by deeptiantony** [comment]
I used the format property for the class int and it was perfect. 
"format":"%d"

**Comment by tdunning** [comment]
Ah... Of course.

I remember now!

Well done.  Could you suggest an addition to the readme in that section if
it isn't describe well?

**Comment by deeptiantony** [comment]
Readme for nested JSON is quite clear now (atleast to me :)) . I suggest that you can add all the properties under each class. Like format property is not mentioned in README.

**Comment by tdunning** [comment]
Good suggestion. I try to do that, but often forget.

Any specific edits are welcome so that I can improve things even before I
can make time for an audit.
