### ISSUE TITLE
gauva dependency is old

### ISSUE THREAD

**Issue by vicenteg** [tdunning/log-synth#29]
Hi,

Was using log-synth with another project that uses guava and ran into some dependency mismatches. It'd be nice to have a newer guava.

Here's the changes I made to update log-synth. Happy to submit a PR if there isn't another reason to keep gauva back.
 
https://github.com/vicenteg/log-synth/commit/685ff5207781496d62f35a6912bae44e22b701d0

**Comment by tdunning** [comment]
Please send a pr.  There isn't any reason to hold back.
