### ISSUE TITLE
“NoSuchMethodErrors” due to multiple versions of org.codehaus.woodstox:stax2-api

### ISSUE THREAD

**Issue by Bing-ok** [tdunning/log-synth#40]
## Issue description:
Hi, there are multiple versions of **_org.codehaus.woodstox:stax2-api_** in **_log-synth_**. As shown in the following dependency tree, according to Maven's "nearest wins" strategy, only **_org.codehaus.woodstox:stax2-api:3.1.1_** can be loaded, **_org.codehaus.woodstox:stax2-api:4.2_** will be shadowed.

However, several methods defined in shadowed version **_org.codehaus.woodstox:stax2-api:4.2_** are referenced by client project via **_com.fasterxml.jackson.dataformat:jackson-dataformat-xml:2.9.10_** but missing in the actually loaded version **_org.codehaus.woodstox:stax2-api:3.1.1_**.

For instance, the following missing method(defined in **_org.codehaus.woodstox:stax2-api:4.2_**) are actually referenced by **_log-synth_**, which will introduce a runtime error(i.e., "NoSuchMethodError") into **_log-synth_**.

**_org.codehaus.stax2.ri.SingletonIterator: org.codehaus.stax2.ri.SingletonIterator create(java.lang.Object)_** is invoked by **_log-synth_** via the following path:
<pre><code>
Invocation path------
&lt;com.mapr.synth.Synth$ReportingWorker: java.lang.Integer call()&gt; log-synth\target\classes
&lt;com.ctc.wstx.dom.WstxDOMWrappingWriter: void writeStartElement(java.lang.String)&gt; Repositories\com\fasterxml\woodstox\woodstox-core\5.3.0\woodstox-core-5.3.0.jar
&lt;com.ctc.wstx.dom.WstxDOMWrappingWriter: void writeStartElement(java.lang.String,java.lang.String)&gt; Repositories\com\fasterxml\woodstox\woodstox-core\5.3.0\woodstox-core-5.3.0.jar
&lt;com.ctc.wstx.dom.WstxDOMWrappingWriter: void createStartElem(java.lang.String,java.lang.String,java.lang.String,boolean)&gt; Repositories\com\fasterxml\woodstox\woodstox-core\5.3.0\woodstox-core-5.3.0.jar
&lt;com.ctc.wstx.dom.WstxDOMWrappingWriter: void writeNamespace(java.lang.String,java.lang.String)&gt; Repositories\com\fasterxml\woodstox\woodstox-core\5.3.0\woodstox-core-5.3.0.jar
&lt;com.ctc.wstx.dom.WstxDOMWrappingWriter: void outputAttribute(java.lang.String,java.lang.String,java.lang.String,java.lang.String)&gt; Repositories\com\fasterxml\woodstox\woodstox-core\5.3.0\woodstox-core-5.3.0.jar
&lt;com.ctc.wstx.dom.WstxDOMWrappingWriter: java.lang.String findOrCreateAttrPrefix(java.lang.String,java.lang.String,com.ctc.wstx.dom.DOMOutputElement)&gt; Repositories\com\fasterxml\woodstox\woodstox-core\5.3.0\woodstox-core-5.3.0.jar
&lt;com.ctc.wstx.sw.OutputElementBase: java.lang.String getExplicitPrefix(java.lang.String)&gt; Repositories\com\fasterxml\woodstox\woodstox-core\5.3.0\woodstox-core-5.3.0.jar
&lt;org.codehaus.stax2.ri.evt.MergedNsContext: java.lang.String getPrefix(java.lang.String)&gt; Repositories\org\codehaus\woodstox\stax2-api\3.1.1\stax2-api-3.1.1.jar
&lt;com.ctc.wstx.sr.InputElementStack: java.util.Iterator getPrefixes(java.lang.String)&gt; Repositories\com\fasterxml\woodstox\woodstox-core\5.3.0\woodstox-core-5.3.0.jar
&lt;com.ctc.wstx.util.DataUtil: java.util.Iterator singletonIterator(java.lang.Object)&gt; Repositories\com\fasterxml\woodstox\woodstox-core\5.3.0\woodstox-core-5.3.0.jar
&lt;org.codehaus.stax2.ri.SingletonIterator: org.codehaus.stax2.ri.SingletonIterator create(java.lang.Object)&gt;
</code></pre>

## Suggested fixing solutions:
1. Use configuration &lt;dependencyManagement&gt; to unify the version of library **_org.codehaus.woodstox:stax2-api_** to be **_4.1_** in the pom file.

2. Change dependency **_com.fasterxml.jackson.dataformat:jackson-dataformat-xml_** from **_2.9.10_** to **_2.10.0.pr1_**.Because the newer version **_com.fasterxml.jackson.dataformat:jackson-dataformat-xml:2.10.0.pr1_** does not invoke the above missing methods, such changing cn solve the problem.
This repair will introduce the following new dependencies:
jakarta.activation:jakarta.activation-api:1.2.1
jakarta.xml.bind:jakarta.xml.bind-api:2.3.2

Please let me know which solution do you prefer? I can submit a PR to fix it.

Thank you very much for your attention.
Best regards,

## Dependency tree----
<pre><code>
[INFO] log-synth:log-synth:jar:0.1-SNAPSHOT
[INFO] +- me.lemire.integercompression:JavaFastPFOR:jar:0.0.13:compile
[INFO] +- org.apache.mahout:mahout-math:jar:0.9:compile
[INFO] |  +- org.apache.commons:commons-math3:jar:3.2:compile
[INFO] |  +- (com.google.guava:guava:jar:16.0:compile - omitted for conflict with 27.1-jre)
[INFO] |  \- (org.slf4j:slf4j-api:jar:1.7.5:compile - omitted for conflict with 1.6.6)
[INFO] +- com.clearspring.analytics:stream:jar:2.5.0:test
[INFO] |  \- it.unimi.dsi:fastutil:jar:6.5.7:test
[INFO] +- com.carrotsearch.randomizedtesting:randomizedtesting-runner:jar:2.1.11:compile
[INFO] |  \- junit:junit:jar:4.10:compile
[INFO] +- org.slf4j:slf4j-api:jar:1.6.6:compile
[INFO] +- org.slf4j:slf4j-log4j12:jar:1.6.6:runtime
[INFO] |  +- (org.slf4j:slf4j-api:jar:1.6.6:runtime - omitted for duplicate)
[INFO] |  \- log4j:log4j:jar:1.2.17:runtime
[INFO] +- args4j:args4j:jar:2.0.23:compile
[INFO] +- com.fasterxml.jackson.core:jackson-databind:jar:2.10.0.pr1:compile
[INFO] |  +- com.fasterxml.jackson.core:jackson-annotations:jar:2.10.0.pr1:compile
[INFO] |  \- com.fasterxml.jackson.core:jackson-core:jar:2.10.0.pr1:compile
[INFO] +- org.codehaus.woodstox:woodstox-core-asl:jar:4.1.4:compile
[INFO] |  +- javax.xml.stream:stax-api:jar:1.0-2:compile
[INFO] |  \- <b>org.codehaus.woodstox:stax2-api:jar:3.1.1:compile</b>
[INFO] |     \- (javax.xml.stream:stax-api:jar:1.0-2:compile - omitted for duplicate)
[INFO] +- com.fasterxml.jackson.dataformat:jackson-dataformat-xml:jar:2.9.10:compile
[INFO] |  +- (com.fasterxml.jackson.core:jackson-core:jar:2.9.10:compile - omitted for conflict with 2.10.0.pr1)
[INFO] |  +- (com.fasterxml.jackson.core:jackson-annotations:jar:2.9.10:compile - omitted for conflict with 2.10.0.pr1)
[INFO] |  +- (com.fasterxml.jackson.core:jackson-databind:jar:2.9.10:compile - omitted for conflict with 2.10.0.pr1)
[INFO] |  +- com.fasterxml.jackson.module:jackson-module-jaxb-annotations:jar:2.9.10:compile
[INFO] |  |  +- (com.fasterxml.jackson.core:jackson-annotations:jar:2.9.10:compile - omitted for conflict with 2.10.0.pr1)
[INFO] |  |  +- (com.fasterxml.jackson.core:jackson-core:jar:2.9.10:compile - omitted for conflict with 2.10.0.pr1)
[INFO] |  |  \- (com.fasterxml.jackson.core:jackson-databind:jar:2.9.10:compile - omitted for conflict with 2.10.0.pr1)
[INFO] |  +- <b>(org.codehaus.woodstox:stax2-api:jar:4.2:compile - omitted for conflict with 3.1.1)</b>
[INFO] |  \- com.fasterxml.woodstox:woodstox-core:jar:5.3.0:compile
[INFO] |     \- <b>(org.codehaus.woodstox:stax2-api:jar:4.2:compile - omitted for conflict with 3.1.1)</b>
[INFO] +- org.freemarker:freemarker:jar:2.3.21:compile
[INFO] +- com.google.guava:guava:jar:27.1-jre:compile
[INFO] |  +- com.google.guava:failureaccess:jar:1.0.1:compile
[INFO] |  +- com.google.guava:listenablefuture:jar:9999.0-empty-to-avoid-conflict-with-guava:compile
[INFO] |  +- com.google.code.findbugs:jsr305:jar:3.0.2:compile
[INFO] |  +- org.checkerframework:checker-qual:jar:2.5.2:compile
[INFO] |  +- com.google.errorprone:error_prone_annotations:jar:2.2.0:compile
[INFO] |  +- com.google.j2objc:j2objc-annotations:jar:1.1:compile
[INFO] |  \- org.codehaus.mojo:animal-sniffer-annotations:jar:1.17:compile
[INFO] +- stax:stax-api:jar:1.0.1:compile
[INFO] +- org.processing:core:jar:3.0b6:compile
[INFO] \- com.tdunning:t-digest:jar:3.0:compile
</code></pre>

**Comment by tdunning** [comment]
Brilliant bug report. Thanks for the effort you put into this.


Do you know what the letters pr1 mean on the Jackson version you suggest?

It looks like I need to move forward on the guava version as well.

**Comment by tdunning** [comment]
What do you think about going to 2.10.5 or 2.11.2?

Would these solve your problem?

**Comment by tdunning** [comment]
Check out the latest trunk to see if it meets your needs.

**Comment by tdunning** [comment]
Ah... Bing-ok is a bot. Closing as works for me with latest changes.

**Comment by Bing-ok** [comment]
Thanks for your support! I have tested version **_2.11.2_** and it can also fix the problem. @tdunning
